baseURL: https://vierja.me/
languageCode: en-us
title: Javier Roberts

defaultContentLanguage: en

permalinks:
  posts: /posts/:title/

paginate: 3

googleAnalytics: G-8P5FCT44XH

enableComments: false
# disqusShortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

social:
  github: https://github.com/javiroberts
  twitter: https://twitter.com/javiroberts
  linkedin: https://linkedin.com/in/javiroberts

params:
  avatarLink: "/images/avatar.jpg"
  author: Javier Roberts
  bio: Software Engineer | CTO @ Wúru
  description: Javier's personal blog
  copyright: "© Copyright 2023 - Javier Roberts"

  showToc: true
  enableRSS: true
  hiddenPostSummaryInHomePage: false
  math: false

  links:
    - name: CV
      path: /cv

  customCSS:
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js
